# docker compose -p mc_24 -f compose.yml --env-file docker.default.env up -d
services:
  db-mc:
    image: postgres:16-alpine
    restart: unless-stopped
    command: ["-c", "datestyle=iso,dmy"]
    volumes:
      - db-data:/var/lib/postgresql/data
      - sql_path:/home/sql
      - script_path:/home/scripts
    environment:
      POSTGRES_DB: mem
      POSTGRES_USER: edissyum
      POSTGRES_PASSWORD: edissyum
      POSTGRES_HOST_AUTH_METHOD: "trust"

  app-mc:
#    image: registry.maarch.org/maarch-dev/courrier:main
    build: #build from docker file instead of pulling image from registry
     context: .
     dockerfile: Dockerfile
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "healthcheck.sh" ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 5s
    volumes:
#      - ${DOCSERVERS_ROOT_PATH}:/opt/maarch/docservers:rw
      - ${CUSTOM_PATH}:/var/www/html/MaarchCourrier/custom:rw
      - sql_path:/var/www/html/MaarchCourrier/sql:rw
      - script_path:/home/scripts
#      - ${LIBRAIRIES_PATH}:/app/librairies
      - ${CRON_CONFIGURATION_PATH}:/etc/cron.d
    ports:
      - ${APP_PORT}:80
    environment:
      LIBRARIES_DIR: /app/librairies
      MAARCH_TMP_DIR: ${MAARCH_TMP_DIR}

volumes:
  db-data:
  sql_path:
  script_path:
